version: '3'

services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  redis-commander:
    image: "rediscommander/redis-commander"
    environment:
      REDIS_HOSTS: redis
    ports:
      - "8081:8081"
    depends_on:
      - redis

  node:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
    command:
      - yarn
      - start
